### ISSUE TITLE
Option to show motor temperature in speed field

### ISSUE THREAD

**Issue by danielnilsson9** [danielnilsson9/bbshd-fw#40]
Add an option to temporary show motor temperature in speed field while push walk is active.

**Comment by danielnilsson9** [comment]
Implemented, display will show Celsius independently of unit setting since it goes to maximum 99 which would not be enough range for fahrenheit.

**Comment by CitizenDev** [comment]
Could this be changed to controller temp sensor for BBS02 since we dont have motor temp sensor?

**Comment by danielnilsson9** [comment]
That is already implemented, if there are multiple sensors the one with the highest value will be shown. There is only one sensor on BBS02 so that will be shown.

**Comment by silenec** [comment]
Would it be possible to have an option to also show other things in speed field such as amps, watts or even cadence? I don't really need speed because I see gps speed on my phone right below the bafang display and on my smart band. Might be useful for testing / adjusting parameters and finding the best motor / human efficiency.

**Comment by danielnilsson9** [comment]
I will consider it, please create an issue so we can see if it is something more people would be interested in.
